### PR TITLE
task/bump werkzeug and other pythong pacakges

### PR DESCRIPTION
**Pull request by nathanfranklin**
## Overview: ##

This PR bumps werkzeug and other packages.

Note that I am ignoring the following as we are not at Flask2.3 yet but we need to switch this by then:
```
'FLASK_ENV' is deprecated and will not be used in Flask 2.3. Use 'FLASK_DEBUG' instead.`
```

## Testing Steps: ##
1. `docker-compose build`
2.  Run portal and test as usual

### CODE REVIEW

**Comment by nathanfranklin** [comment]
@ myself and others, resources download needs to be rechecked as I think the unit test is failing locally due to bump.

**Comment by nathanfranklin** [comment]
@ myself and others, resources download needs to be rechecked as I think the unit test is failing locally due to bump.

**Review by taoteg — APPROVED** [review]
Works perfectly.

**Comment by nathanfranklin** [comment]
> @ myself and others, resources download needs to be rechecked as I think the unit test is failing locally due to bump.

@taoteg , i think we need in `shapely==1.8.5` as unit tests are failing locally. will PR this sometime.

**Pull request merged**
