### PR TITLE
remove code related to projections selector

### PR DESCRIPTION
**Pull request by ryamase**
## Overview: ##
Remove Projections selector

## Related Jira tickets: ##

* [COOKS-123](https://jira.tacc.utexas.edu/browse/COOKS-123)

## Summary of Changes: ##
Remove frontend code related to the Projections selector

## Testing Steps: ##
1. Go to https://cep.test/protx/dash/analytics
2. Make sure there is no Projections dropdown menu, no Demographics dropdown menu, and no Year dropdown menu.
3. Make sure the correct chart is shown on the right; it needs to be the chart with 'Predicted Number of Cases per 100K persons' as the x-axis label.

## UI Photos:
Screen Shot 2022-10-20 at 4 17 13 PM

### CODE REVIEW

**Comment by ryamase** [comment]
I haven't touched the backend code, so the dispatch and saga still has a variable called analyticsType but it is hard-coded to 'pred_per_100k'. Let me know if you want me to revise the backend code.

**Comment by nathanfranklin** [comment]
> I haven't touched the backend code, so the dispatch and saga still has a variable called analyticsType but it is hard-coded to 'pred_per_100k'. Let me know if you want me to revise the backend code.

> I haven't touched the backend code, so the dispatch and saga still has a variable called analyticsType but it is hard-coded to 'pred_per_100k'. Let me know if you want me to revise the backend code.

that makes sense to me.  as it sounds like a route is needed in the near future.

**Comment by nathanfranklin** [comment]
I'm just realizing that the `year` dropdown is not needed in the Analytics view anymore.  can we drop this here in this PR?

**Comment by ryamase** [comment]
Yeah, it seems like the analytics data is not tied to a year based on what's in the database -- makes sense to remove the year dropdown completely. I'll remove it. 
I think we'll need to refactor DisplaySelector at some point.

**Review by nathanfranklin — APPROVED** [review]
LGTM 👍

**Review by sophia-massie — APPROVED** [review]
LGTM

**Pull request merged**
