### PR TITLE
Use env variables to pin database versions

### PR DESCRIPTION
**Pull request by nathanfranklin**
## Overview: ##

A PR to pin databases so we are aware what source code goes with what database versions.  

Users would need to place any new databases and then update the .env file.  

**if we like this**, then we need to add these env variables to Core-Deployments 's protx docker-compose files 

In this PR:
* the database versions are env variables and so pinned in .env (for docker-compose)
*  some refactoring of where those database paths are defined in our python code (i.e. protx/utils/db.py)

## Related Jira tickets: ##

None

## Testing Steps: ##
0. Ensure you have the pinned databases in your ~/protx-data folder
1. docker exec -it protx python3 scripts/run_queries.py --clear-cache
2. Run unit tests
3. Try app

### CODE REVIEW

**Review by taoteg — APPROVED** [review]
Love seeing this! Not only does it remove the disconnect in comms between WMA & DMC groups, but the code is actually cleaner. Great work!

**Comment by taoteg** [comment]
Should we make a task to ensure we add the new settings to the Deployments Repo as well?

**Review by sophia-massie — APPROVED** [review]
LGTM! Thanks for doing this.

**Comment by nathanfranklin** [comment]
>Should we make a task to ensure we add the new settings to the Deployments Repo as well, or do you just want to update the repo when you merge this branch and close the loop then?

@taoteg ,  added follow on task https://jira.tacc.utexas.edu/browse/WG-7

**Pull request merged**
