### PR TITLE
Bug/COOKS-284: Add bootstrap scripts and center loader.

### PR DESCRIPTION
**Pull request by duckonomy**
## Overview: ##
Fixed issue where initial loading only shows *Loading...*

## Related Jira tickets: ##

* [COOKS-284](https://jira.tacc.utexas.edu/browse/COOKS-284)

## Summary of Changes: ##
The bootstraps scripts were missing from `dash.html` (hence no spinner icon).
So added that and vertically centered spinner.

## Testing Steps: ##
1. Ensure that loader icon shows and is centered (horizontally and vertically).

### CODE REVIEW

**Review by taoteg — APPROVED** [review]
LGTM!

**Review by nathanfranklin — CHANGES_REQUESTED** [review]
LGTM on dev 👍 

In a deployed scenario, the spinning icon is still missing (I ran the image locally by merging https://github.com/TACC/protx-dashboard/pull/23 locally into this branch while testing).  So maybe the template used then by protx-client/dist/index.html needs to be updated?  or maybe there is a way to configure that these scripts are added by vite or in the build step.  I wonder how this is handled in CEP?

**Comment by taoteg** [comment]
@duckonomy  Is this fixed now? I can't tell from the state of the ticket.

**Comment by duckonomy** [comment]
> @duckonomy Is this fixed now? I can't tell from the state of the ticket.

@taoteg I just pushed a commit addressing Nathan's comment on production/staging!

**Review by nathanfranklin — APPROVED** [review]
LGTM.  Tested the built client from image locally 👍

**Pull request merged**
