### PR TITLE
Update pyproject.toml python and numpy versions

### PR DESCRIPTION
**Pull request by taoteg**
## Overview: ##

```
As of numpy 1.21.2, there is a maximum version of python. Numpy 1.21.2 (to 1.21.5 as time of writing this answer) requires python version greater than 3.7 but strictly lower than 3.11.

Also, Python 3.7 is no longer supported in release 1.22.0 and later of numpy. Python support has been dropped. This is rather strict, there are changes that require Python >= 3.8.

The Python versions supported for this release on Numpy (v.1.23.2) are 3.8-3.11.
```

- This edit should allow us to resolve the numpy version conflict.  
- Bumped numpy up to the next-to-latest release (which has a deprecation in it and I didn't want to trigger a side-effect by accident).

## Related Jira tickets: ##

* None

## Testing Steps: ##

1. Run project.

### CODE REVIEW

**Comment by taoteg** [comment]
I need to run the update process locally sop the lockfile updates. Ill do that in a bit and reopen the PR when the build checks pass.

**Comment by taoteg** [comment]
Updated and fixed. All good.

**Review by nathanfranklin — APPROVED** [review]
LGTM.  tested locally 👍

**Review by duckonomy — APPROVED** [review]
LGTM!

**Pull request merged**
